openapi: "3.0.0"
servers:
  - url: /api
info:
  version: 1.0.0
  title: File storage

paths:
  /files:
    get:
      summary: List all files
      operationId: listFiles
      tags:
        - files
      responses:
        '200':
          description: Array of files
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /upload:
    post:
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: File response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    File:
      type: object
      required:
        - id
        - name
        - path
        - size
      properties:
        id:
          type: string
        filename:
          type: string
        path:
          type: string
        size:
          type: integer
          format: int64
    FileList:
      type: array
      items:
        $ref: "#/components/schemas/File"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
